In [26]:
import pandas as pd

In [27]:
import math

def harmonize_agrupacion_id(agrupacion_id):
    if pd.isna(agrupacion_id):
        return "000000"
    else:
        try:
            # Attempt to convert string to float and then to integer
            return str(int(float(agrupacion_id))).zfill(6)
        except ValueError:
            # If conversion fails, return original string value
            return agrupacion_id

In [28]:
eleccion = pd.read_csv('./../datos/BD/eleccion_table.csv')
eleccion

    eleccion_id   año eleccion_tipo recuento_tipo padron_tipo
0             1  2011          PASO    PROVISORIO      NORMAL
1            10  2017          PASO    PROVISORIO      NORMAL
2             9  2017          PASO    PROVISORIO     COMANDO
3             8  2017       GENERAL    PROVISORIO      NORMAL
4             7  2017       GENERAL    PROVISORIO     COMANDO
5             5  2015       GENERAL    PROVISORIO      NORMAL
6             4  2015     BALLOTAGE    PROVISORIO      NORMAL
7            17  2023          PASO    PROVISORIO      NORMAL
8             0  2011       GENERAL    PROVISORIO      NORMAL
9             6  2015          PASO    PROVISORIO      NORMAL
10            3  2013          PASO    PROVISORIO      NORMAL
11            2  2013       GENERAL    PROVISORIO      NORMAL
12           16  2021          PASO    PROVISORIO      NORMAL
13           15  2021          PASO    PROVISORIO     COMANDO
14           14  2019          PASO    PROVISORIO      NORMAL
15           13  2019          PASO    PROVISORIO     COMANDO
16           12  2019       GENERAL    PROVISORIO      NORMAL
17           11  2019       GENERAL    PROVISORIO     COMANDO

In [29]:
import pandas as pd

In [30]:
pd.read_csv('./../datos/BD/agrupacion_lista_table.csv')

,eleccion_id,distrito_id,agrupacion_id,votos_tipo,lista_numero,lista_nombre
0,1,1,509.0,POSITIVO,3072.0,LISTA A - OTRO PAIS ES POSIBLE
1,1,1,509.0,POSITIVO,3074.0,LISTA C - UNIR
2,1,1,509.0,POSITIVO,3075.0,LISTA D - JUAN BAUTISTA ALBERDI
3,1,1,509.0,POSITIVO,3073.0,LISTA B - POR EL PAIS
4,1,4,3.0,POSITIVO,3021.0,INTRANSIGENCIA - LISTA R
...,...,...,...,...,...,...
7131,12,24,NaN,BLANCO,NaN,NaN
7132,12,24,NaN,IMPUGNADO,NaN,NaN
7133,12,24,NaN,NULO,NaN,NaN
7134,12,24,NaN,RECURRIDO,NaN,NaN
7135,11,24,NaN,COMANDO,NaN,NaN

In [41]:
cargo = pd.read_csv('./../datos/BD/cargo_table.csv')

agrup_lista = pd.read_csv('./../datos/BD/agrupacion_lista_table.csv')
agrup_lista['agrupacion_id'] = agrup_lista['agrupacion_id'].apply(harmonize_agrupacion_id)
agrup_lista['lista_numero'] = agrup_lista['lista_numero'].apply(harmonize_agrupacion_id)
agrup_lista

agrup = agrup_lista[['eleccion_id',	'agrupacion_id']].drop_duplicates()
lista = agrup_lista[['eleccion_id',	'agrupacion_id', 'lista_numero']].drop_duplicates()

agrup

      eleccion_id agrupacion_id
0               1        000509
4               1        000003
8               1        000037
11              1        000133
12              1        000057
...           ...           ...
7024           12        02-737
7025           12       02-1912
7026           12        02-884
7027           12        02-888
7032           12        02-792

[1595 rows x 2 columns]

In [32]:
cargo = pd.read_csv('./../datos/BD/cargo_tags.csv')
cargo

   cargo_id                          cargo_nombre cargo_tag
0         3                     Diputado Nacional        DN
1         1                            Presidente        PR
2         4                            Gobernador        GB
3         6                   Diputado Provincial        DP
4         2                      Senador Nacional        SN
5         5                    Senador Provincial        SP
6        10                              Concejal        CO
7         9  Parlamentarios Mercosur Provinciales        MP
8         8    Parlamentarios Mercosur Nacionales        MN
9         7                            Intendente        IN

In [33]:
# agrup_lista.groupby(['agrupacion_id'])['agrupacion_nombre'].unique().apply(lambda x: x[0:2]).to_frame().reset_index()

# Si queremos un solo valor por agrupacion id
# agrup_names = agrup_lista.groupby(['eleccion_id', 'distrito_id', 'agrupacion_id']).agrupacion_nombre.unique().astype(str).reset_index()

In [34]:
# fuerzas = pd.read_csv('./../datos/info/agrupacion_nombre_weight_labels.csv')

# agrup_fzas = agrup_lista.merge(fuerzas, how = 'left')
# agrup_fzas.loc[agrup_fzas.agrupacion_id == '000000', 'fuerza'] = ''
# agrup_fzas['fuerza'] = agrup_fzas['fuerza'].fillna('OTROS')
# fuerzas = agrup_fzas[['agrupacion_nombre', 'fuerza']].drop_duplicates()

In [35]:
import glob
import os

## list of csv files
csv_files = glob.glob('./../datos/BD/votos_eleccion_*_table.csv')

## list of dataframes
# dfs = [pd.read_csv(f) for f in csv_files]
dfs = []
for f in csv_files:
    # Read the CSV file into a DataFrame
    df = pd.read_csv(f)
    
    # Filter the DataFrame using loc and the condition (for example, where 'cargo_id' is 1 or 3)
    df = df.loc[df['cargo_id'].isin([1, 3])]
    dfs.append(df)


data = pd.concat(dfs, ignore_index=True)

data['agrupacion_id'] = data['agrupacion_id'].apply(harmonize_agrupacion_id)
# data['lista_numero'] = data['lista_numero'].apply(harmonize_agrupacion_id)
# agrup_lista.lista_numero.value_counts()

/tmp/ipykernel_8145/1033292653.py:12: DtypeWarning: Columns (3,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)
/tmp/ipykernel_8145/1033292653.py:12: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)
/tmp/ipykernel_8145/1033292653.py:12: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)
/tmp/ipykernel_8145/1033292653.py:12: DtypeWarning: Columns (3,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)
/tmp/ipykernel_8145/1033292653.py:12: DtypeWarning: Columns (6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)
/tmp/ipykernel_8145/1033292653.py:12: DtypeWarning: Columns (3,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)
/tmp/ipykernel_8145/1033292653.py:12: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)
/tmp/ipykernel_8145/1033292653.py:12: DtypeWarning: Columns (6,7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)
/tmp/ipykernel_8145/1033292653.py:12: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)
/tmp/ipykernel_8145/1033292653.py:12: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)
/tmp/ipykernel_8145/1033292653.py:12: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(f)

In [36]:
# data.loc[(data.agrupacion_nombre == 'JUNTOS POR EL CAMBIO') & (data.eleccion_id == 16)].votos_cantidad.sum()

In [37]:
data.nunique()

distrito_id               24
seccionprovincial_id      16
seccion_id               135
circuito_id             2817
mesa_id                 9228
cargo_id                   2
agrupacion_id            397
agrupacion_nombre        515
lista_numero             436
votos_tipo                 6
votos_cantidad           384
eleccion_id               18
dtype: int64

In [38]:
csv_files

['./../datos/BD/votos_eleccion_5_table.csv',
 './../datos/BD/votos_eleccion_8_table.csv',
 './../datos/BD/votos_eleccion_1_table.csv',
 './../datos/BD/votos_eleccion_4_table.csv',
 './../datos/BD/votos_eleccion_6_table.csv',
 './../datos/BD/votos_eleccion_11_table.csv',
 './../datos/BD/votos_eleccion_3_table.csv',
 './../datos/BD/votos_eleccion_15_table.csv',
 './../datos/BD/votos_eleccion_12_table.csv',
 './../datos/BD/votos_eleccion_10_table.csv',
 './../datos/BD/votos_eleccion_0_table.csv',
 './../datos/BD/votos_eleccion_14_table.csv',
 './../datos/BD/votos_eleccion_2_table.csv',
 './../datos/BD/votos_eleccion_13_table.csv',
 './../datos/BD/votos_eleccion_17_table.csv',
 './../datos/BD/votos_eleccion_9_table.csv',
 './../datos/BD/votos_eleccion_16_table.csv',
 './../datos/BD/votos_eleccion_7_table.csv']

## Votos por agrupacion, provincia, eleccion, cargo

In [39]:
data.votos_cantidad.sum()
# 850253087

452084637

In [42]:
simil_nombre = agrup_lista.groupby(['eleccion_id', 'distrito_id', 'agrupacion_id']).agrupacion_nombre.first().reset_index()

merged_data = data.merge(simil_nombre)

In [43]:

merged_data['agrupacion_nombre'] = merged_data['agrupacion_nombre'].replace('CAMBIEMOS BUENOS AIRES', 'CAMBIEMOS')
merged_data['agrupacion_nombre'] = merged_data['agrupacion_nombre'].replace('JUNTOS', 'JUNTOS POR EL CAMBIO', regex=False)
merged_data['agrupacion_nombre'] = merged_data['agrupacion_nombre'].str.title()

In [44]:
# merged_data.loc[(merged_data.agrupacion_nombre == 'JUNTOS POR EL CAMBIO') & (merged_data.eleccion_id == 16)].votos_cantidad.sum()

In [45]:
out = merged_data.groupby(['eleccion_id', 'cargo_id', 'agrupacion_nombre', 'votos_tipo'])[['votos_cantidad']].sum().reset_index()
out

,eleccion_id,cargo_id,agrupacion_nombre,votos_tipo,votos_cantidad
0,0,1,Alianza Compromiso Federal,POSITIVO,1714385
1,0,1,Alianza Frente Amplio Progresista,POSITIVO,3624518
2,0,1,Alianza Frente De Izquierda Y De Los Trabajadores,POSITIVO,497082
3,0,1,Alianza Frente Para La Victoria,POSITIVO,11593023
4,0,1,Alianza Frente Popular,POSITIVO,1264609
...,...,...,...,...,...
986,17,3,Union Popular Federal,POSITIVO,15698
987,17,3,Union Por La Patria,POSITIVO,5069810
988,17,3,Union Por San Luis,POSITIVO,46949
989,17,3,Unite Por La Libertad Y La Dignidad,POSITIVO,2118
990,17,3,Unión Y Libertad,POSITIVO,6553

In [46]:
# out.loc[(out.agrupacion_nombre == 'JUNTOS POR EL CAMBIO') & (out.eleccion_id == 16)].votos_cantidad.sum()

In [47]:
pd.options.display.max_rows = 200

In [48]:
n = 4
main = out.groupby(['eleccion_id', 'cargo_id', 'votos_tipo']).apply(lambda x: x.nlargest(n, 'votos_cantidad')).reset_index(drop=True).rename(columns={'votos_cantidad': 'votos_nacional'})
main

,eleccion_id,cargo_id,agrupacion_nombre,votos_tipo,votos_nacional
0,0,1,Alianza Frente Para La Victoria,POSITIVO,11593023
1,0,1,Alianza Frente Amplio Progresista,POSITIVO,3624518
2,0,1,Alianza Unión Para El Desarrollo Social,POSITIVO,2395056
3,0,1,Alianza Compromiso Federal,POSITIVO,1714385
4,0,3,Alianza Frente Para La Victoria,POSITIVO,9486670
5,0,3,Alianza Frente Amplio Progresista,POSITIVO,2524726
6,0,3,Alianza Unión Para El Desarrollo Social,POSITIVO,1403800
7,0,3,Alianza Compromiso Federal,POSITIVO,1157041
8,1,1,Alianza Frente Para La Victoria,POSITIVO,5529799
9,1,1,Alianza Frente Popular,POSITIVO,1526449
10,1,1,Alianza Union Para El Desarrollo Social - Udeso,POSITIVO,1442921
11,1,1,Alianza Frente Amplio Progresista,POSITIVO,1317791
12,1,3,Alianza Frente Para La Victoria,POSITIVO,4225818
13,1,3,Alianza Frente Amplio Progresista,POSITIVO,799961
14,1,3,Alianza Union Para El Desarrollo Social - Udeso,POSITIVO,579722
15,1,3,Alianza Frente Popular,POSITIVO,554690
16,2,3,Frente Para La Victoria,POSITIVO,6798175
17,2,3,Frente Renovador,POSITIVO,3911926
18,2,3,Frente Progresista Civico Y Social,POSITIVO,2034441
19,2,3,Union Civica Radical,POSITIVO,1369655
20,3,3,Frente Para La Victoria,POSITIVO,3997938
21,3,3,Frente Renovador,POSITIVO,3081574
22,3,3,Frente Progresista Civico Y Social,POSITIVO,1760652
23,3,3,Union Civica Radical,POSITIVO,1126207
24,4,1,Cambiemos,POSITIVO,12903301
25,4,1,Frente Para La Victoria,POSITIVO,12198441
26,5,1,Alianza Frente Para La Victoria,POSITIVO,9002242
27,5,1,Alianza Cambiemos,POSITIVO,8382610
28,5,1,Alianza Unidos Por Una Nueva Alternativa (Una),POSITIVO,5211705
29,5,1,Alianza Frente De Izquierda Y De Los Trabajadores,POSITIVO,798031
30,5,3,Alianza Frente Para La Victoria,POSITIVO,8084299
31,5,3,Alianza Cambiemos,POSITIVO,4009802
32,5,3,Alianza Unidos Por Una Nueva Alternativa (Una),POSITIVO,2974576
33,5,3,Cambiemos,POSITIVO,2928287
34,6,1,Alianza Frente Para La Victoria,POSITIVO,8424749
35,6,1,Alianza Cambiemos,POSITIVO,6595914
36,6,1,Alianza Unidos Por Una Nueva Alternativa (Una),POSITIVO,4525497
37,6,1,Alianza Progresistas,POSITIVO,769316
38,6,3,Alianza Frente Para La Victoria,POSITIVO,7573741
39,6,3,Alianza Cambiemos,POSITIVO,4820560
40,6,3,Alianza Unidos Por Una Nueva Alternativa (Una),POSITIVO,2085660
41,6,3,Alianza Union Por Cordoba,POSITIVO,697945
42,8,3,Cambiemos,POSITIVO,7015942
43,8,3,Unidad Ciudadana,POSITIVO,3417542
44,8,3,Frente Justicialista,POSITIVO,1050380
45,8,3,Frente De Izquierda Y De Los Trabajadores,POSITIVO,1039416
46,10,3,Cambiemos,POSITIVO,5660590
47,10,3,Unidad Ciudadana,POSITIVO,2972061
48,10,3,1Pais,POSITIVO,1334438
49,10,3,Frente Justicialista,POSITIVO,1120965
50,12,1,Frente De Todos,POSITIVO,12473709
51,12,1,Juntos Por El Cambio,POSITIVO,10470607
52,12,1,Consenso Federal,POSITIVO,1599707
53,12,1,Frente De Izquierda Y De Trabajadores - Unidad,POSITIVO,561214
54,12,3,Frente De Todos,POSITIVO,11174215
55,12,3,Juntos Por El Cambio,POSITIVO,8924988
56,12,3,Consenso Federal,POSITIVO,1140826
57,12,3,Frente De Izquierda Y De Trabajadores - Unidad,POSITIVO,718261
58,14,1,Frente De Todos,POSITIVO,11622428
59,14,1,Juntos Por El Cambio,POSITIVO,7825208
60,14,1,Consenso Federal,POSITIVO,2007035
61,14,1,Frente De Izquierda Y De Trabajadores - Unidad,POSITIVO,697776
62,14,3,Frente De Todos,POSITIVO,10478736
63,14,3,Juntos Por El Cambio,POSITIVO,6923002
64,14,3,Consenso Federal,POSITIVO,1332201
65,14,3,Frente De Izquierda Y De Trabajadores - Unidad,POSITIVO,714601
66,16,3,Frente De Todos,POSITIVO,6480057
67,16,3,Juntos Por El Cambio,POSITIVO,5988221
68,16,3,Frente De Izquierda Y De Trabajadores - Unidad,POSITIVO,969751
69,16,3,Hacemos Por Córdoba,POSITIVO,446545
70,17,1,La Libertad Avanza,POSITIVO,7116352
71,17,1,Juntos Por El Cambio,POSITIVO,6698029
72,17,1,Union Por La Patria,POSITIVO,6460689
73,17,1,Hacemos Por Nuestro Pais,POSITIVO,907437
74,17,3,Juntos Por El Cambio,POSITIVO,5443198
75,17,3,Union Por La Patria,POSITIVO,5069810
76,17,3,La Libertad Avanza,POSITIVO,4913772
77,17,3,Frente De Izquierda Y De Trabajadores - Unidad,POSITIVO,606857

In [49]:
data.head()

,distrito_id,seccionprovincial_id,seccion_id,circuito_id,mesa_id,cargo_id,agrupacion_id,agrupacion_nombre,lista_numero,votos_tipo,votos_cantidad,eleccion_id
0,21,0.0,13,000341,4354,1,000131,ALIANZA FRENTE PARA LA VICTORIA,NaN,POSITIVO,89,5
1,21,0.0,13,000341,4354,1,000133,ALIANZA COMPROMISO FEDERAL,NaN,POSITIVO,4,5
2,21,0.0,13,00362A,6441,1,000131,ALIANZA FRENTE PARA LA VICTORIA,NaN,POSITIVO,108,5
3,21,0.0,13,00362A,6441,1,000133,ALIANZA COMPROMISO FEDERAL,NaN,POSITIVO,4,5
4,21,0.0,13,00362A,6444,1,000131,ALIANZA FRENTE PARA LA VICTORIA,NaN,POSITIVO,89,5

In [50]:
main.head()

,eleccion_id,cargo_id,agrupacion_nombre,votos_tipo,votos_nacional
0,0,1,Alianza Frente Para La Victoria,POSITIVO,11593023
1,0,1,Alianza Frente Amplio Progresista,POSITIVO,3624518
2,0,1,Alianza Unión Para El Desarrollo Social,POSITIVO,2395056
3,0,1,Alianza Compromiso Federal,POSITIVO,1714385
4,0,3,Alianza Frente Para La Victoria,POSITIVO,9486670

In [51]:
data_ = data.copy()

In [52]:
data_['agrupacion_nombre'] = data_['agrupacion_nombre'].replace('CAMBIEMOS BUENOS AIRES', 'CAMBIEMOS')
data_['agrupacion_nombre'] = data_['agrupacion_nombre'].replace('JUNTOS', 'JUNTOS POR EL CAMBIO')
data_['agrupacion_nombre'] = data_['agrupacion_nombre'].str.title()


data_ = data_.merge(main, how = 'left')

## Limpiar

data_['agrupacion_nombre'] = data_['agrupacion_nombre'].str.title().str.strip()

data_['agrupacion_nombre_'] = data_['agrupacion_nombre'].mask(data_['votos_nacional'].isnull()).fillna('Resto')

data_agrup = data_.groupby(['distrito_id', 'seccion_id', 'circuito_id', 'mesa_id', 'cargo_id', 'agrupacion_nombre_', 'votos_tipo', 'eleccion_id'])['votos_cantidad'].sum()
data_agrup = data_agrup.reset_index()

In [57]:
data_agrup.sample(10)

,distrito_id,seccion_id,circuito_id,mesa_id,cargo_id,agrupacion_nombre_,votos_tipo,eleccion_id,votos_cantidad
6266078,2,117,000964,43,3,Resto,IMPUGNADO,0,0
8960409,5,21,000128,2290,1,Resto,IMPUGNADO,4,0
14228400,21,18,000092,6475,3,Resto,IMPUGNADO,1,0
6961865,2,132,000290,9007,3,Resto,COMANDO,7,0
10764335,13,2,00026A,477,3,Frente De Izquierda Y De Trabajadores - Unidad,POSITIVO,14,18
7483560,4,1,00010D,1228,3,Resto,POSITIVO,0,79
15222454,24,1,000U11,176,3,Resto,RECURRIDO,14,0
7498951,4,1,00010G,1371,3,Resto,RECURRIDO,2,0
7567472,4,1,00011E,1831,3,Resto,IMPUGNADO,6,0
4407835,2,70,000589,1036,3,Resto,IMPUGNADO,17,0

In [58]:
data_agrup.dtypes

distrito_id            int64
seccion_id             int64
circuito_id           object
mesa_id                int64
cargo_id               int64
agrupacion_nombre_    object
votos_tipo            object
eleccion_id            int64
votos_cantidad         int64
dtype: object

In [59]:
data_prov = data_agrup.groupby(['eleccion_id', 'cargo_id', 'agrupacion_nombre_', 'votos_tipo', 'distrito_id'])[['votos_cantidad']].sum()
data_prov.to_csv('./../datos/out/votos_agrup_prov.csv')
data_prov.votos_cantidad.sum()
# 849583464
# 404565719

452084637

In [60]:
data_secc = data_agrup.groupby(['eleccion_id', 'cargo_id', 'agrupacion_nombre_', 'votos_tipo', 'distrito_id', 'seccion_id'])[['votos_cantidad']].sum()
data_secc.to_csv('./../datos/out/votos_agrup_secc.csv')
data_secc.votos_cantidad.sum()

452084637

In [61]:
## Seccion_id no es necesario, alcanza con provincia-circuito. Pero lo agregamos porque a traves de los circuitos se relaciona el seccion_id con el id de deptos en IGN.
data_circ = data_agrup.groupby(['eleccion_id', 'cargo_id', 'agrupacion_nombre_', 'votos_tipo', 'distrito_id', 'seccion_id', 'circuito_id'])[['votos_cantidad']].sum()
data_circ.to_csv('./../datos/out/votos_agrup_circ.csv')
data_circ.votos_cantidad.sum()

452084637

In [62]:
# data_prov.to_csv('./../datos/out/votos_agrup_prov.csv')
data_prov.votos_cantidad.sum()

452084637

In [63]:
data_prov = pd.read_csv('./../datos/out/votos_agrup_prov.csv')#.merge(prov_ids)
data_prov.votos_cantidad.sum()

# 404.565.719

452084637

In [ ]:
xx

NameError: name 'xx' is not defined

In [ ]:
# Mezclar los datos con un subconjunto de columnas de agrup_lista y luego eliminar los duplicados
# merged_data = data.merge(agrup_lista[['eleccion_id', 'agrupacion_id', 'agrupacion_nombre']].drop_duplicates())
simil_nombre = agrup_lista.groupby(['eleccion_id', 'distrito_id', 'agrupacion_id']).agrupacion_nombre.first().reset_index()
merged_data = data.merge(simil_nombre).merge(fuerzas)

# Mezclar el conjunto de datos resultante con el conjunto de datos de cargo
merged_data = merged_data.merge(cargo)

# Agrupar el conjunto de datos resultante por varias columnas y agregar la columna votos_cantidad sumando sus valores
grouped_data = merged_data.groupby(['eleccion_id', 'cargo_id', 'fuerza']).agg({'votos_cantidad': 'sum'})

# Restablecer el índice del conjunto de datos resultante y crear un nuevo índice
table = grouped_data.unstack('fuerza')/1e3
table.round(1) # miles

                     votos_cantidad                                           \
fuerza                              IZQUIERDA MASSA   OTROS    PERON     PRO
eleccion_id cargo_id
0           1                 908.7     497.1   NaN  1660.8  11593.0     NaN
            2                 977.4     279.4   NaN   998.4   5310.6     NaN
            3                1968.4     494.7   NaN  2688.3   9871.4   368.0
            4                1352.4     244.5   NaN  1478.7   5033.6     NaN
            5                 684.6     132.2   NaN   780.9   2669.0     NaN
...                             ...       ...   ...     ...      ...     ...
16          3                1472.6    1129.4  49.8  3749.9   6480.1  8599.0
            5                 467.7     289.4   NaN   838.2   1633.4  2155.2
            6                 574.6     443.6   NaN  1249.9   2523.7  3045.7
            7                   0.2       NaN   NaN     2.8      2.7     0.2
            10                814.9     539.0   NaN  1560.4   3240.2  3599.0


fuerza               PROVINCIAL SOCIALISTA     UCR
eleccion_id cargo_id
0           1            1714.4     3624.5  2395.1
            2             910.4     1078.3  1167.0
            3            1676.7     2616.2  2443.4
            4             125.3     1013.2  1273.9
            5             267.1      548.6   458.7
...                         ...        ...     ...
16          3            1227.8       50.1     NaN
            5              32.5        NaN     NaN
            6              32.5        NaN     NaN
            7               NaN        NaN     NaN
            10             34.0        NaN     NaN

[98 rows x 9 columns]

In [ ]:
table.votos_cantidad.sum()

fuerza
               63999.189
IZQUIERDA      28451.893
MASSA          66209.025
OTROS          75686.495
PERON         319551.758
PRO           223334.396
PROVINCIAL     37392.734
SOCIALISTA     17216.743
UCR            17741.231
dtype: float64

In [ ]:
eleccion_tags = pd.read_csv('./../datos/BD/eleccion_tags.csv')
distritos = pd.read_csv('./../datos/BD/distrito_table.csv')

In [ ]:
## Tabla para verificar que los ppales agrupaciones de cada provincia tienen bien colocado el nombre de fuerza

In [ ]:
# # # data = merged_data.loc[merged_data.cargo_id.isin([1, 3])].copy()

# # # votos_prov_agrup = data.groupby(['eleccion_id', 'cargo_nombre', 'distrito_id', 'agrupacion_nombre']).votos_cantidad.sum()

# votos_prov_agrup = votos_prov_agrup.reset_index().merge(eleccion_tags).merge(distritos)
# votos_prov_agrup = votos_prov_agrup[['año', 'eleccion_tipo', 'padron_tipo', 'distrito_nombre', 'cargo_nombre', 'agrupacion_nombre', 'votos_cantidad']]
# main_agrupaciones = votos_prov_agrup.sort_values('votos_cantidad', ascending=False).groupby(['año', 'eleccion_tipo', 'padron_tipo', 'distrito_nombre', 'cargo_nombre']).head(3)
# tabla_checks = main_agrupaciones.merge(fuerzas).sort_values(['año', 'eleccion_tipo', 'padron_tipo', 'distrito_nombre', 'cargo_nombre'])
# tabla_checks.to_csv('./../datos/info/agrupacion_fuerza_checks.csv', index=False)
# tabla_checks.head(12)

,año,eleccion_tipo,padron_tipo,distrito_nombre,cargo_nombre,agrupacion_nombre,votos_cantidad,fuerza
179,2011,GENERAL,NORMAL,Buenos Aires,Diputado Nacional,Alianza Frente para la Victoria,4460986,PERON
638,2011,GENERAL,NORMAL,Buenos Aires,Diputado Nacional,Alianza Frente Amplio Progresista,1018572,SOCIALISTA
675,2011,GENERAL,NORMAL,Buenos Aires,Diputado Nacional,Alianza Unión para el Desarrollo Social,905064,UCR
178,2011,GENERAL,NORMAL,Buenos Aires,Presidente,Alianza Frente para la Victoria,4704016,PERON
637,2011,GENERAL,NORMAL,Buenos Aires,Presidente,Alianza Frente Amplio Progresista,1251277,SOCIALISTA
676,2011,GENERAL,NORMAL,Buenos Aires,Presidente,Alianza Unión para el Desarrollo Social,810882,UCR
211,2011,GENERAL,NORMAL,Catamarca,Diputado Nacional,Alianza Frente para la Victoria,120806,PERON
661,2011,GENERAL,NORMAL,Catamarca,Diputado Nacional,Alianza Frente Amplio Progresista,7237,SOCIALISTA
1157,2011,GENERAL,NORMAL,Catamarca,Diputado Nacional,Alianza Frente Cívico y Social,39715,SOCIALISTA
210,2011,GENERAL,NORMAL,Catamarca,Presidente,Alianza Frente para la Victoria,130983,PERON
660,2011,GENERAL,NORMAL,Catamarca,Presidente,Alianza Frente Amplio Progresista,9591,SOCIALISTA
691,2011,GENERAL,NORMAL,Catamarca,Presidente,Alianza Unión para el Desarrollo Social,33649,UCR

In [ ]:
data_prov = merged_data.groupby(['eleccion_id', 'cargo_id', 'fuerza', 'distrito_id']).agg({'votos_cantidad': 'sum'})
data_prov.to_csv('./../datos/out/votos_prov.csv')
data_prov.votos_cantidad.sum()
# 849583464

849583464

In [ ]:
data_secc = merged_data.groupby(['eleccion_id', 'cargo_id', 'fuerza', 'distrito_id', 'seccion_id']).agg({'votos_cantidad': 'sum'})
data_secc.to_csv('./../datos/out/votos_secc.csv')
data_secc.votos_cantidad.sum()

849583464

In [ ]:
## Seccion_id no es necesario, alcanza con provincia-circuito. Pero lo agregamos porque a traves de los circuitos se relaciona el seccion_id con el id de deptos en IGN.
data_circ = merged_data.groupby(['eleccion_id', 'cargo_id', 'fuerza', 'distrito_id', 'seccion_id', 'circuito_id']).agg({'votos_cantidad': 'sum'})
data_circ.to_csv('./../datos/out/votos_circ.csv')
data_circ.votos_cantidad.sum()

849583464

In [ ]:
table.votos_cantidad.sum()

fuerza
               63999.189
IZQUIERDA      28451.893
MASSA          66209.025
OTROS          75686.495
PERON         319551.758
PRO           223334.396
PROVINCIAL     37392.734
SOCIALISTA     17216.743
UCR            17741.231
dtype: float64